"""Add subscription fields to user table

Revision ID: ff723d01685e
Revises: 
Create Date: 2025-09-27 14:58:39.916753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff723d01685e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('plan', sa.String(), nullable=True))
    op.add_column('users', sa.Column('subscription_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'expires_at')
    op.drop_column('users', 'subscription_id')
    op.drop_column('users', 'plan')
    # ### end Alembic commands ###
